[project]
authors = ["Chaebeom Sheen <cauchybs@snu.ac.kr>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "bioinfo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = "==1.26.4"
uv = ">=0.4.9,<0.5"
scipy = ">=1.14.1,<2"
pyinstrument = ">=4.7.3,<5"
jax = ">=0.4.31,<0.5"
numba = ">=0.60.0,<0.61"

[pypi-dependencies]
python-dotenv = ">=1.0.1, <2"
